# Generated by Django 5.0.2 on 2024-02-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TSU', 'Tecnico superior universitario'), ('Ing', 'Ingenieria'), ('Lic', 'Licenciatura'), ('M', 'Maestria')], max_length=20, verbose_name='nivel')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
    ]
