# Generated by Django 5.0.2 on 2024-02-29 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AddField(
            model_name='career',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Abrreviatura'),
            preserve_default=False,
        ),
    ]
